org: sean14
app: express-template
service: express-template
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-west-1
  stage: dev

functions:
  api:
    handler: app.handler
    events:
      - httpApi: '*'
